#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update

sudo apt-get install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

sudo service nginx restart
