#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+     at the root with a curl GET request.
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s/listen 80 default_server;/listen 80;/"
sudo sed -i "add_header X-Served-By $HOSTNAME;"

sudo service nginx restart
