#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100.

num=1

while [ $num -le 100 ]; do
	fizz=$((num % 3))
	buzz=$((num % 5))

	if [ $fizz -eq 0 ] && [ $buzz -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $fizz -eq 0 ]; then
		echo "Fizz"
	elif [ $buzz -eq 0 ]; then
		echo "Buzz"
	else
		echo "$num"
	fi
	((num++))
done
